### ISSUE TITLE
pllpy fails to compile

### ISSUE THREAD

**Issue by sdwfrost** [kgori/pllpy#1]
Hi @kgori 

I'm trying to get pllpy to build, but installing, either via pip or locally, using Python2 or 3, fails. Can you take a look to see what has changed since the last commit?

**Comment by kgori** [comment]
OK. I heard the Stamatakis lab are redoing PLL from scratch, so it could be something upstream.

**Comment by kgori** [comment]
I don't think it was anything upstream. I've fixed a few things and pushed a new version (0.1.18) to pypi. It builds for me using python2, but python3 is lagging behind because I still haven't figured out how to wrap C strings in a way that is compatible with both Pythons.
Could you try building it again and pass on any error messages?

**Comment by sdwfrost** [comment]
Will do. The Python2/3 string differences are annoying, even with [documentation](http://docs.cython.org/en/latest/src/tutorial/strings.html). I take the simple way out and only support Python3. Is there any chance of a separate branch for Python3?

**Comment by kgori** [comment]
It appears that putting this tag 
`#cython: c_string_type=str, c_string_encoding=ascii`
at the top of the cython .pyx file will solve all your python 2/3 string problems.
The latest version (0.2.0) on PyPI should be compatible with python 2 and 3. If you could try it out and let me know if it works for you I'd appreciate it.
